#ifndef GCIRCULARBUFFER_H
#define GCIRCULARBUFFER_H

#include <gCircularBuffer.inc>

GCIRCULAR_BUFFER_TYPE_INC(void*, Ptr);

GCIRCULAR_BUFFER_TYPE_INC(float, Float);
GCIRCULAR_BUFFER_TYPE_INC(double, Double);

GCIRCULAR_BUFFER_TYPE_INC(int64_t, Int64);
GCIRCULAR_BUFFER_TYPE_INC(int32_t, Int32);
GCIRCULAR_BUFFER_TYPE_INC(int16_t, Int16);

#endif /* GCIRCULARBUFFER_H */
